/* Automatically generated by './build/bin/build-entry.js' */

import Statistics from '../packages/statistics/index.js';
import Toast from '../packages/toast/index.js';

const components = [
  Statistics,
  Toast
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.0',
  install,
  Statistics,
  Toast
};
