/* Automatically generated by './build/bin/build-entry.js' */
import './fonts/iconfont.css'
import Statistics from '../packages/statistics/index.js'
import MessageBox from '../packages/message-box/index.js'
import Icon from '../packages/icon/index.js'
import Qrcode from '../packages/qrcode/index.js'

const components = [Statistics, Icon, Qrcode]

// eslint-disable-next-line no-unused-vars
const install = function (Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '1.0.2',
  install,
  Statistics,
  MessageBox,
  Icon,
  Qrcode
}
